title: Super Mario Bros is NP-Hard
description: A website explaining why Super Mario Bros is NP-Hard using the Just the Docs theme.
theme: just-the-docs

url: https://erickhiu.github.io/mario-npc/

aux_links:
  Template Repository: https://erickhiu.github.io/mario-npc

color_scheme: mario

just_the_docs:
  custom_css: "assets/css/custom.css"
  math: true
